sudo: required
language: python
python: "2.7"
services:
  - docker

before_install:
  - docker build -t xlsform/pyxform .
env:
  - "RUNTESTS=nosetests"
  - "RUNTESTS='nosetests -w pyxform/tests_v1/ -s'"
script:
  - docker run -t xlsform/pyxform $RUNTESTS
